#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d      ﭮ    

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#feh --bg-fill $HOME/Downloads/blue-sky/wallpapers/blue3.png
feh --bg-fill $HOME/Pictures/wllp/3.jpg

xsetroot -cursor_name left_ptr &
~/.config/polybar/./launch.sh
picom --experimental-backends &
