#!/bin/bash

paths=(
    "/home/adrs/vimwiki/personal"
    "/home/adrs/.task/"
)
cdate=$(date +'%Y-%m-%d %H:%M:%S')

for path in "${paths[@]}"
do
    cd "$path" || { echo "ERROR"; exit; }
    git add .
    git commit -m "Feat: Update $cdate"
    git push origin main
done
