#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server
if [ $# -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME"
else
	scp  -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
