-- GENERAL
require "user.options"
require "user.wichkey"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"

-- PLUGINS

require "user.alpha"
require "user.lualine"
require "user.bufferline"
require "user.scrollbar"
require "user.nvim-tree"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.indentline"
require "user.project"
require "user.telescope"
require "user.toggleterm"
require "user.impatient"
require "user.autocommands"
require "user.illuminate"
require "user.dap"
require "user.session-manager"
require "user.ufo"
require "user.vim-closetag"

-- require "user.hop"
-- require "user.surround"
