-- ╭─────────────────────────╮
-- │ Dependencies            │
-- ╰─────────────────────────╯
require "user.impatient_cfg"
require "user.telescope_cfg"
require "user.notify_cfg"
require "user.neogit_cfg"
-- require "user.shade"
require "user.project_cfg"

-- ╭─────────────────────────╮
-- │ Setup Colorscheme       │
-- ╰─────────────────────────╯
require "user.kanagawa_cfg"
require "user.aquarium_cfg"
require "user.grubox-baby_cfg"
require "user.tokyodark_cfg"
require "user.tokyonight_cfg"
require "user.everforest_cfg"
require "user.onedark_cfg"
require "user.nord_cfg"
require "user.material_cfg"
require "user.neon_cfg"
require "user.colorscheme"

-- ╭─────────────────────────╮
-- │ General                 │
-- ╰─────────────────────────╯
require "user.options"
require "user.autocommands"
require "user.wichkey_cfg"
require "user.keymaps"
require "user.toggleOpt"
require "user.clr-cmd"
require "user.hydra-windows_cfg"
require "user.hydra-git_cfg"
require "user.hydra-markdown_cfg"
require "user.hydra-wiki_cfg"
require "user.hydra-rest_cfg"
require "user.plugins"

-- ╭─────────────────────────╮
-- │ Plugins                 │
-- ╰─────────────────────────╯
require "user.alpha_cfg"
require "user.lualine_cfg"
require "user.lualine-t_cfg"
require "user.bufferline_cfg"
require "user.scrollbar_cfg"
require "user.nvim-tree_cfg"
require "user.cmp_cfg"
require "user.treesitter_cfg"
require "user.lsp"
require "user.autopairs_cfg"
require "user.comment_cfg"
require "user.gitsigns_cfg"
require "user.indentline_cfg"
require "user.toggleterm_cfg"
require "user.illuminate_cfg"
require "user.dap_cfg"
require "user.session-manager_cfg"
require "user.ufo_cfg"
require "user.custom-fold"
require "user.hop_cfg"
require "user.zen-mode_cfg"
require "user.true-zen_cfg"
require "user.snip-run_cfg"
require "user.jaq-nvim_cfg"
require "user.twilight_cfg"
require "user.nvim-neoclip_cfg"
require "user.surfer"
require "user.nvim-spectre_cfg"
require "user.toggle-lsp_cfg"
require "user.rest_cfg"
require "user.dbui_cfg"
require "user.color-picker_cfg"
require "user.colorizer_cfg"
-- require "user.ale_cfg"
require "user.telescope-pickers"
require "user.copilot"
