vim.cmd "let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.jsx,*.js,*.tsx'"
vim.cmd "let g:closetag_xhtml_filenames = '*.xhtml,*.jsx,*.js,*.tsx'"
vim.cmd "let g:closetag_filetypes = 'html,xhtml,phtml,jsx,js,tsx,javascript.jsx'"
vim.cmd "let g:closetag_xhtml_filetypes = 'xhtml,jsx,js,tsx,javascript.jsx'"
vim.cmd "let g:closetag_emptyTags_caseSensitive = 1"
vim.cmd "let g:closetag_regions = { 'typescript.tsx': 'jsxRegion,tsxRegion', 'javascript.jsx': 'jsxRegion', 'typescriptreact': 'jsxRegion,tsxRegion' }"
vim.cmd "let g:closetag_shortcut = '>'"
vim.cmd "let g:closetag_close_shortcut = '<leader>>'"
